export const AppUrl = {
    Login: 'backoffice',
    Summary: 'summary',
    Branch: 'branch',
    SaleInfo: 'saleInfo',
    ExamChart: 'exchart',
    MonthlyMeeting: 'monthlyMeeting',
    NewsManagement: 'newsManagement',
    NewsEdit: 'newsEdit',
    Home: 'home',
    Thumbnail: 'thumbnail',
    Gallery: 'gallery',
    NEWSContent: 'NEWSContent',
    FoodManagement: 'foodManagement',
    TrainningContent: 'trainningContent',
    TrainningManagement: 'trainningManagement',
    Chat: 'chat',
    Mobile: 'mobile',
    Contract: 'contract',
    ContractPayment: 'contractpayment/:cust_no/:cust_name/:id/:con_date/:tot_amt/:period/:pay_amt/:discount/:balance',
    TargetReport: 'targetreport',
    PayReport: 'payreport',
    BankSelection: 'bankselection/:con_no/:cust_no/:pay_amt'
};
